### ISSUE TITLE
Swagger doc generation failed when there is a function bounded to an entity with enum parameter

### ISSUE THREAD

**Issue by kfstorm** [rbeauchamp/Swashbuckle.OData#103]
When there is a function bounded to an entity with enum parameter, the document generation will fail with below error:

```
500 : {"message":"An error has occurred.","exceptionMessage":"The parameter 'EnumValue=ValueOne' is not in scope.","exceptionType":"Microsoft.OData.Core.ODataException","stackTrace":" at Microsoft.OData.Core.UriParser.Parsers.FunctionCallBinder.BindSegmentParameters(ODataUriParserConfiguration configuration, IEdmOperation functionOrOpertion, ICollection`1 segmentParameterTokens)
 at Microsoft.OData.Core.UriParser.Parsers.ODataPathParser.TryBindingParametersAndMatchingOperation(String identifier, String parenthesisExpression, IEdmType bindingType, ODataUriParserConfiguration configuration, ICollection`1& boundParameters, IEdmOperation& matchingOperation)
 at Microsoft.OData.Core.UriParser.Parsers.ODataPathParser.TryCreateSegmentForOperation(ODataPathSegment previousSegment, String identifier, String parenthesisExpression)
 at Microsoft.OData.Core.UriParser.Parsers.ODataPathParser.CreateNextSegment(String text)
 at Microsoft.OData.Core.UriParser.Parsers.ODataPathParser.ParsePath(ICollection`1 segments)
 at Microsoft.OData.Core.UriParser.Parsers.ODataPathFactory.BindPath(ICollection`1 segments, ODataUriParserConfiguration configuration)
 at Microsoft.OData.Core.UriParser.ODataUriParser.Initialize()
......"} http://localhost:4074/swagger/docs/v1
```

The root cause is invalid URL template. The expected template is like `GET /odata/Products({id})/Default.IsEnumValueMatch(EnumValue=SwashbuckleODataSample.Models.MyEnum'{EnumValue}')` but actually `GET /odata/Products({id})/Default.IsEnumValueMatch(EnumValue=SwashbuckleODataSample.Models.MyEnum{EnumValue})`. Single quotes are missing.

**Comment by kfstorm** [comment]
#104

**Comment by rbeauchamp** [comment]
@kfstorm: I really appreciate your pull request. Fix is available on NuGet: https://www.nuget.org/packages/Swashbuckle.OData/2.18.4

**Comment by kfstorm** [comment]
@rbeauchamp Glad to help. Very useful tool.
