### ISSUE TITLE
Error is SwaggerUI - Nullable object must have a value

### ISSUE THREAD

**Issue by scubasteveb** [rbeauchamp/Swashbuckle.OData#22]
I have setup a Odata project based on the sample using the customprovider and document filter, however I receive this error when generating the UI:

0x800a139e - JavaScript runtime error: 500 : {"Message":"An error has occurred.","ExceptionMessage":"Nullable object must have a value.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)\r\n   at System.Nullable`1.get_Value()\r\n   at Swashbuckle.OData.MapToDefault.Map(Parameter parameter, Int32 index, HttpActionDescriptor actionDescriptor)\r\n   at Swashbuckle.OData.SwaggerToApiExplorerMapper.<>c__DisplayClass2_0.<Map>b__0(IParameterMapper mapper)\r\n   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()\r\n   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at Swashbuckle.OData.SwaggerToApiExplorerMapper.Map(Parameter parameter, Int32 index, HttpActionDescriptor actionDescriptor)\r\n   at Swashbuckle.OData.ODataApiExplorer.GetHttpParameterDescriptor(Parameter parameter, Int32 index, HttpActionDescriptor actionDescriptor)\r\n   at Swashbuckle.OData.ODataApiExplorer.GetParameterDescription(Parameter parameter, Int32 index, HttpActionDescriptor actionDescriptor)\r\n   at Swashbuckle.OData.ODataApiExplorer.<>c__DisplayClass19_0.<CreateParameterDescriptions>b__0(Parameter parameter, Int32 index)\r\n   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at Swashbuckle.OData.ODataApiExplorer.CreateParameterDescriptions(Operation operation, HttpActionDescriptor actionDescriptor)\r\n   at Swashbuckle.OData.ODataApiExplorer.GetApiDescription(HttpActionDescriptor actionDescriptor, HttpMethod httpMethod, Operation operation, ODataRoute route, String potentialPathTemplate)\r\n   at Swashbuckle.OData.ODataApiExplorer.GetApiDescription(HttpMethod httpMethod, ODataRoute oDataRoute, String potentialPathTemplate, Operation potentialOperation, HttpControllerDescriptor controllerDesciptor, HttpRequestMessage request, HttpRequestContext requestContext)\r\n   at Swashbuckle.OData.ODataApiExplorer.GetApiDescription(HttpMethod httpMethod, ODataRoute oDataRoute, String potentialPathTemplate, Operation potentialOperation)\r\n   at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions(ODataRoute oDataRoute, String potentialPathTemplate, PathItem potentialOperations)\r\n   at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions(ODataRoute oDataRoute)\r\n   at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions()\r\n   at System.Lazy`1.CreateValue()\r\n   at System.Lazy`1.LazyInitValue()\r\n   at System.Lazy`1.get_Value()\r\n   at Swashbuckle.OData.ODataApiExplorer.get_ApiDescriptions()\r\n   at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion)\r\n   at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion)\r\n   at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Web.Http.HttpServer.<>n__FabricatedMethod9(HttpRequestMessage , CancellationToken )\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"} http://localhost:2015/swagger/docs/v1

**Comment by rbeauchamp** [comment]
Hi can you please post a gist or enough code so that I can reproduce your issue?

**Comment by scubasteveb** [comment]
https://gist.github.com/scubasteveb/6420447d0d894f5b7f62

**Comment by rbeauchamp** [comment]
Thanks @scubasteveb! I'll research and get back to you.

**Comment by stimpy77** [comment]
I think I have this issue too.


	<Error><Message>An error has occurred.</Message><ExceptionMessage>Could not generate sample value for query parameter type array and format null</ExceptionMessage><ExceptionType>System.Exception</ExceptionType><StackTrace>   at Swashbuckle.OData.ODataApiExplorer.GenerateSampleQueryParameterValue(Parameter queryParameter)
	   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
	   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
	   at Swashbuckle.OData.ODataApiExplorer.GenerateSampleQueryParameterValues(Operation operation)
	   at Swashbuckle.OData.ODataApiExplorer.GenerateSampleODataAbsoluteUri(String pathTemplate, Operation operation)
	   at Swashbuckle.OData.ODataApiExplorer.GetApiDescription(HttpMethod httpMethod, ODataRoute oDataRoute, String potentialPathTemplate, Operation potentialOperation)
	   at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions(ODataRoute oDataRoute, String potentialPathTemplate, PathItem potentialOperations)
	   at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions(ODataRoute oDataRoute)
	   at Swashbuckle.OData.ODataApiExplorer.GetApiDescriptions()
	   at System.Lazy`1.CreateValue()
	   at System.Lazy`1.LazyInitValue()
	   at System.Lazy`1.get_Value()
	   at Swashbuckle.OData.ODataApiExplorer.get_ApiDescriptions()
	   at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion)
	   at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion)
	   at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
	   at System.Web.Http.Cors.CorsMessageHandler.&lt;&gt;n__FabricatedMethod3(HttpRequestMessage , CancellationToken )
	   at System.Web.Http.Cors.CorsMessageHandler.&lt;SendAsync&gt;d__0.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at System.Web.Http.Tracing.ITraceWriterExtensions.&lt;TraceBeginEndAsyncCore&gt;d__18`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at System.Web.Http.Owin.PassiveAuthenticationMessageHandler.&lt;SendAsync&gt;d__0.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at System.Web.Http.Tracing.ITraceWriterExtensions.&lt;TraceBeginEndAsyncCore&gt;d__18`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at System.Web.Http.Tracing.ITraceWriterExtensions.&lt;TraceBeginEndAsyncCore&gt;d__18`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at System.Web.Http.HttpServer.&lt;SendAsync&gt;d__0.MoveNext()</StackTrace></Error>

**Comment by rbeauchamp** [comment]
Hey @scubasteveb, I downloaded and ran your gist code but could not reproduce your issue. I think it was related to the functions I see defined in your webapiconfig. I've fixed various issues that I found with functions in the latest release [v2.6.1](https://www.nuget.org/packages/Swashbuckle.OData/2.6.1). Please give it a try and let me know if it fixes your issue.

**Comment by rbeauchamp** [comment]
Hmmm... it may be related to the optional function parameters which I haven't tested.

**Comment by rbeauchamp** [comment]
@scubasteveb, I'll re-open this if you are still having the same issue.
