### ISSUE TITLE
Exception thrown for non implemented routes

### ISSUE THREAD

**Issue by darewreck54** [rbeauchamp/Swashbuckle.OData#39]
I noticed that when you don't implement a potential route such as a "PUT" an exception gets thrown 

   at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.GetInitialCandidateList(HttpControllerContext controllerContext, Boolean ignoreVerbs)
   at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.GetInitialCandidateWithParameterListForRegularRoutes(HttpControllerContext controllerContext, Boolean ignoreVerbs)
   at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.FindMatchingActions(HttpControllerContext controllerContext, Boolean ignoreVerbs)
   at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.Controllers.ApiControllerActionSelector.SelectAction(HttpControllerContext controllerContext)
   at System.Web.OData.Routing.ODataActionSelector.SelectAction(HttpControllerContext controllerContext)
   at Swashbuckle.OData.Descriptions.HttpRequestMessageExtensions.GetHttpActionDescriptor(HttpRequestMessage request)

I think there is a chance that an application would not want to implement some of these routes, but they would have to deal with this exception being thrown.  Also if you just return null from your SelectAction method for your custom route, I don't believe the Swashbuckle.Odata library will handle it gracefully and will either crash or not load the rest of the controller for the swagger UI.

Thanks,
D

**Comment by rbeauchamp-lendingtree** [comment]
Hey D, the [OrdersController](http://swashbuckleodata.azurewebsites.net/swagger/ui/index#!/Orders) is an example of a controller that doesn't contain all potential routes: it doesn't support "PUT". No exceptions are thrown in that scenario though. Can you please provide info to reproduce your scenario?

**Comment by rbeauchamp** [comment]
Will reopen if able to reproduce.

**Comment by darewreck54** [comment]
Hi,

So after debugging the issue it seems that the exception was being thrown for other reasons relating to my code.  Without the source code and only the DLL, you wouldn't be able to debug these issues.

To help others who come across issue like I have, I've identified two locations where I had issue and the exception and error message were not clear so it took me a while to figure.  I imagine that this would make it more usable for others, but i'm not sure how you want to handle error handling in your code.

1) SwaggerRouteStrategy::GenerateSampleODataPath (..)
   oDataPathRouteConstraint.PathHandler.Parse(model....) will throw an Exception if the controller in the path is incorrect when defining custom routes.  Perhaps some validation that the controller specified in the custom route url relates to the controller. Unless you references the Odata code vs. the .dll you would never catch this error and would be debugging aimlessly

2) HttpRequestMessageExtensions:GetHttpActionDescriptor(..)
  var controller = controllerDescriptor.CreateController(request); will throw an exception if the controller constructor is not defined and complains that a default constructor needs to be implemented.  However, if you use dependency injection into the constructor and it wasn't set up correctly, this could result in CreateController exception also being thrown as well.  Perhaps correct the error message because it's a little miss leading.

Thanks,
D
