### ISSUE TITLE
Exception "An item with the same key has already been added." when using CustomProvider ODataSwaggerProvider

### ISSUE THREAD

**Issue by isaacllopisaracil** [rbeauchamp/Swashbuckle.OData#72]
I get an exception on SendAsync of my main handler when the request for http://localhost/swagger/ui/index comes in.

The exception is "An item with the same key has already been added" and the stacktrace is added below. It only happens when adding `c.CustomProvider((defaultProvider) => new ODataSwaggerProvider(defaultProvider, c));` to the `SwaggerConfig`, otherwise Swashbuckle works fine, only with the non-OData controllers in my project.

---Stacktrace---
` at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary``2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable``1 source, Func``2 keySelector, Func``2 elementSelector, IEqualityComparer``1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable``1 source, Func``2 keySelector, Func``2 elementSelector)
   at Swashbuckle.OData.Descriptions.OperationExtensions.GenerateSamplePathParameterValues(Operation operation)
   at Swashbuckle.OData.Descriptions.OperationExtensions.GenerateSampleODataUri(Operation operation, String serviceRoot, String pathTemplate)
   at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.CreateHttpRequestMessage(HttpMethod httpMethod, Operation potentialOperation, SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig)
   at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(HttpMethod httpMethod, Operation potentialOperation, SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig)
   at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig)
   at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.<>c__DisplayClass3_0.<Generate>b__1(SwaggerRoute potentialSwaggerRoute)
   at System.Linq.Enumerable.<SelectManyIterator>d__16``2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16``2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63``1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16``2.MoveNext()
   at System.Collections.Generic.List``1..ctor(IEnumerable``1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable``1 source)
   at Swashbuckle.OData.CollectionExtentions.ToCollection[T](IEnumerable``1 source)
   at Swashbuckle.OData.Descriptions.ODataApiExplorer.GetApiDescriptions()
   at System.Lazy``1.CreateValue()
   at System.Lazy``1.LazyInitValue()
   at System.Lazy``1.get_Value()
   at Swashbuckle.OData.Descriptions.ODataApiExplorer.get_ApiDescriptions()
   at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion)
   at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion)
   at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Web.Http.Cors.CorsMessageHandler.<>n__FabricatedMethod3(HttpRequestMessage , CancellationToken )
   at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__0.MoveNext()`
---End of stacktrace---

I'm using NuGet packages:

- Swashbuckle.OData (2.16.2)
- Swashbuckle (5.2.2, cannot use higher versions due to restriction in dependencies from Swashbuckle.OData)
- Swashbuckle.Core (5.2.2, cannot use higher versions due to restriction in dependencies from Swashbuckle.OData)
- Microsoft.OData.Core (6.14.0)
- Microsoft.AspNet.OData (5.8.0)
- Microsoft.OData.Edm (6.14.0)
- Microsoft.Spatial (6.14.0)
- Microsoft.AspNet.WebApi.WebHost (5.2.3)
- Microsoft.AspNet.WebApi.Client (5.2.3)
- Microsoft.AspNet.WebApi.Core (5.2.3)
- Newtonsoft.Json (8.0.2)
- Flurl (1.0.10)

**Comment by rbeauchamp** [comment]
@isaacllopisaracil can you please provide enough info so that I can reproduce this issue? maybe some sample code?

**Comment by rbeauchamp-lendingtree** [comment]
Please try v2.18.0. It fixed the issue found in #77. Closing this issue until we get enough information or sample code to reproduce.

**Comment by kellerd** [comment]
I'm using 2.18.3, I get this when I reference a recursive relationship.  Exception thrown at the .ToCollection

            config.AddCustomSwaggerRoute(oDataRoute, "/Organizations({OrganizationId})/Organizations")
            .Operation(HttpMethod.Get)
            .PathParameter<decimal>("OrganizationId")
            ;
