### ISSUE TITLE
Microsoft.Restier.WebApi.Model.OperationAttribute causes an error when Release configuration selected

### ISSUE THREAD

**Issue by cilerler** [rbeauchamp/Swashbuckle.OData#92]
### Reproduce steps

Simply add following codes into the API and set the configuration to **RELEASE**

> again this issue does not show up on DEBUG configuration

```
[Operation]
public double MostImportant(IEnumerable<Person> bindingParameter)
{
    return Convert.ToDouble(bindingParameter.First().Id);
}
```
### Expected result

Fully generated Swagger UI output
### Actual result

```
{
    "message": "An error has occurred.",
    "exceptionMessage": "Object reference not set to an instance of an object.",
    "exceptionType": "System.NullReferenceException",
    "stackTrace": "   
   at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.MapForRestierIfNecessary(HttpRequestMessage request, HttpActionDescriptor actionDescriptor)
   at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(HttpMethod httpMethod, Operation potentialOperation, SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig)
   at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.GetActionDescriptors(SwaggerRoute potentialSwaggerRoute, HttpConfiguration httpConfig)
   at Swashbuckle.OData.Descriptions.SwaggerRouteStrategy.<>c__DisplayClass3_0.<Generate>b__1(SwaggerRoute potentialSwaggerRoute)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.OData.CollectionExtentions.ToCollection[T](IEnumerable`1 source)
   at Swashbuckle.OData.Descriptions.ODataApiExplorer.GetApiDescriptions()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Swashbuckle.OData.ODataSwaggerProvider.GetApiDescriptionsFor(String apiVersion)
   at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion)
   at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()
   "
}
```

**Comment by rbeauchamp-lendingtree** [comment]
@cilerler Interesting. Thanks for posting this!

**Comment by bastienlemaitre** [comment]
Hi !
I got the same problem.. Any solutions now ?

**Comment by cilerler** [comment]
@rbeauchamp is there any chance you may look into this? 🙏
