### ISSUE TITLE
Problem using DataContractAttribute with DataMemberAttribute with modified member name

### ISSUE THREAD

**Issue by TomMuijsers** [rbeauchamp/Swashbuckle.OData#95]
This might be related to #79.

When using the `DataContractAttribute` on a type with a `DataMemberAttribute` on each member (one or more with a modified member name) an exception occurs:

``` json
500: {
    "Message": "An error has occurred.",
    "ExceptionMessage": "Precondition failed: currentProperty != null",
    "ExceptionType": "System.Diagnostics.Contracts.__ContractsRuntime+ContractException",
    "StackTrace": " at System.Diagnostics.Contracts.__ContractsRuntime.TriggerFailure(ContractFailureKind kind, String msg, String userMessage, String conditionTxt, Exception inner)
 at System.Diagnostics.Contracts.__ContractsRuntime.ReportFailure(ContractFailureKind kind, String msg, String conditionTxt, Exception inner)
 at System.Diagnostics.Contracts.__ContractsRuntime.Requires(Boolean condition, String msg, String conditionTxt)
 at Swashbuckle.OData.SchemaRegistryExtensions.GetEdmPropertyName(MemberInfo currentProperty, IEdmStructuredType edmType)
 at Swashbuckle.OData.SchemaRegistryExtensions.ApplyEdmModelPropertyNamesToSchema(SchemaRegistry registry, IEdmModel edmModel, Type type)
 at Swashbuckle.OData.SchemaRegistryExtensions.GetOrRegisterResponseType(SchemaRegistry registry, IEdmModel edmModel, Type type)
 at Swashbuckle.OData.ODataSwaggerProvider.CreateOperation(ApiDescription apiDescription, SchemaRegistry schemaRegistry)
 at Swashbuckle.OData.ODataSwaggerProvider.CreatePathItem(IEnumerable`1 apiDescriptions, SchemaRegistry schemaRegistry)
 at Swashbuckle.OData.ODataSwaggerProvider.<>c__DisplayClass4_0.<GetSwagger>b__3(IGrouping`2 group)
 at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
 at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
 at Swashbuckle.OData.ODataSwaggerProvider.GetSwagger(String rootUrl, String apiVersion)
 at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
 at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"
}
```

For example, I applied the `DataContractAttribute` on the `Brand` type in `ModelSchemaTests`:

``` c#
[DataContract]
public class Brand
{
    [Key]
    [DataMember]
    public long Id { get; set; }

    [DataMember]
    public string Code { get; set; }

    [DataMember]
    public string Name { get; set; }

    [DataMember(Name = "Something")]
    public string Description { get; set; }
}
```

When I look at the method `ApplyEdmModelPropertyNamesToSchema` in `SchemaRegistryExtensions`

``` c#
private static void ApplyEdmModelPropertyNamesToSchema(SchemaRegistry registry, IEdmModel edmModel, Type type)
{
    var entityReference = registry.GetOrRegister(type);
    if (entityReference.@ref != null)
    {
        var definitionKey = entityReference.@ref.Replace("#/definitions/", string.Empty);
        var schemaDefinition = registry.Definitions[definitionKey];
        var edmType = edmModel.GetEdmType(type) as IEdmStructuredType;
        if (edmType != null)
        {
            var edmProperties = new Dictionary<string, Schema>();
            foreach (var property in schemaDefinition.properties)
            {
                var currentProperty = type.GetProperty(property.Key, BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance);
                var edmPropertyName = GetEdmPropertyName(currentProperty, edmType);
                if (edmPropertyName != null)
                {
                    edmProperties.Add(edmPropertyName, property.Value);
                }
            }
            schemaDefinition.properties = edmProperties;
        }
    }
}
```

it appears that the properties in `schemaDefinition.properties` have already been renamed (i.e. `Description` has been renamed to `something`). Then in the line

``` c#
var currentProperty = type.GetProperty(property.Key, BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance);
```

the property `something` isn't found on the `Brand` type, because on the type the property is still called `Description`. This results in `currentProperty` being `null`, which is passed to `GetEdmPropertyName`, where the check `Contract.Requires(currentProperty != null)` takes place, resulting in the error mentioned earlier.

Do you have a solution to this problem? Or can you point me in the right direction to fix this error?

**Comment by rbeauchamp-lendingtree** [comment]
@TomMuijsers Thanks for the detailed analysis. I don't have a solution right now but my first thought is that the fix would involve making GetEdmPropertyName and GetProperty consistent with each other: both using the DataMember Name (or both not using).

**Comment by MichalCar** [comment]
I don't have modified name. The problem disappeared when I remove the serialize attribute from the entity. When I remove it I get the Public property. When I put it I get the private fields in your code.

**Comment by he-man71** [comment]
Do you have any update on this issue? I am having the exact same problem as described.

**Comment by nurf3d** [comment]
I am having the same issue with version 3.4.0.
